__base__: ../DualCervix_grayscale.yaml

trainer:
    init_args:
        callbacks:
            change_item:
                -   - -1
                    -   init_args:
                            monitor: val/map_50
                            filename: 'epoch:{epoch}-val_map_50:{val/map_50:.4g}'
                            mode: max