__base__:
    - ../default_runtime.yaml
    - ../datasets/DualCervix/DualCervixRegistration/DualCervixRegistration_color.yaml
    - ../models/GAN/CycleGAN.yaml

trainer:
    init_args:
        strategy: ddp

data:
    init_args:
        data_loader_config:
            batch_size: 1
            num_workers: 3
            prefetch_factor: 2
