__base__:
    - ../default_runtime.yaml
    - ../datasets/DualCervix/DualCervixRegistration/DualCervixRegistration_color.yaml
    - ../models/GAN/pix2pix.yaml

trainer:
    init_args:
        strategy: ddp

data:
    init_args:
        data_loader_config:
            batch_size: 16
            num_workers: 8
            prefetch_factor: 2
