__base__:
    - ../default_runtime.yaml
    - ../datasets/DualCervix/DualCervixRegistration/DualCervixRegistration_color.yaml
    - ../models/VxmDense/VxmDense_deeplabv3.yaml

model:
    init_args:
        loss_config:
            seg:
                weight: 0.0

trainer:
    init_args:
        strategy: ddp

data:
    init_args:
        data_loader_config:
            batch_size: 16
            num_workers: 8
            prefetch_factor: 2
