model:
    class_path: models.models.vxm_dense.VxmDense
    init_args:
        backbone:
            class_path: models.backbones.Unet.Unet
            init_args:
                inshape: [ 512, 512 ]
                infeats: 6
        inshape: [ 512, 512 ]
        final_nf: 16
        normalize_config:
            acid:
                mean: [ 107.5614013671875, 108.2771987915039, 157.57847595214844 ]
                std: [ 15.73247241973877, 13.8170747756958, 24.39257049560547 ]
            iodine:
                mean: [ 43.90464401245117, 71.49726867675781, 123.6583023071289 ]
                std: [ 14.21172046661377, 18.04821014404297, 34.25565719604492 ]
        loss_config:
            img:
                module:
                    class_path: models.losses.losses.NCC
                weight: 1.0
            grad:
                module:
                    class_path: models.losses.losses.Grad
                    init_args:
                        penalty: 2
                        loss_mult: 81
                weight: 1.0
            seg:
                module:
                    class_path: models.losses.losses.Dice
                weight: 1.0

optimizer_config:
    optimizer:
        class_path: torch.optim.AdamW
        init_args:
            lr: 1.0e-3
            weight_decay: 0.01
    lr_scheduler:
        scheduler:
            class_path: torch.optim.lr_scheduler.ReduceLROnPlateau
            init_args:
                mode: min
                factor: 0.1
                patience: 5
                cooldown: 2
            monitor: train/loss
        warmup_config:
            warmup_iters: 500