__base__:
    - resnet50_cataract.yaml
    - ../../models/image_classifier/resnet50_with_label.yaml

model:
    init_args:
        model:
            init_args:
                img_out_channels: 128
                label_in_channels: 6
                label_out_channels: 128
                head:
                    num_classes: 7
                    in_channels: 256