__base__:
    - resnet50_cataract.yaml
    - ../../models/image_classifier/resnet50_dimly.yaml

model:
    init_args:
        model:
            init_args:
                head:
                    num_classes: 7
                dimly_head:
                    num_classes: 7