__base__:
    - ../../default_runtime.yaml
    - ../../models/image_classifier/resnet50.yaml
    - ../../datasets/cataract/cataract_kfold_classification.yaml
    - ../../schedules/schedule_1x.yaml

model:
    init_args:
        model:
            init_args:
                head:
                    num_classes: 7
        optimizer_config:
            optimizer:
                lr: 5e-3

data:
    init_args:
        data_loader_config:
            batch_size: 8
            num_workers: 8
            prefetch_factor: 2
