__base__:
    - resnet50_cataract.yaml
    - ../../models/image_classifier/resnet50_transformer_mae_learn_label.yaml

model:
    init_args:
        model:
            init_args:
                num_labels: 4
                fusion_transformer_cfg:
                    transformer_cfg:
                        num_patches: 6
                decoder_transformer_cfg:
                    transformer_cfg:
                        num_patches: 6
                label_configs:
                    default:
                        loss:
                            loss_weight: 1.0
                head:
                    num_classes: 7
                    loss:
                        loss_weight: 0.0

trainer:
    strategy: ddp