__base__:
    - resnet50_with_label_cataract.yaml
    - ../../models/image_classifier/resnet50_with_label_no_fusion.yaml

model:
    init_args:
        model:
            init_args:
                use_attention: false
                head:
                    num_classes: 7
                    in_channels: 128
                label_head:
                    num_classes: 7
                    in_channels: 128