__base__:
    - resnet50_transformer_with_label_cataract.yaml
    - ../../models/image_classifier/resnet50_transformer_distillation_label.yaml

model:
    init_args:
        model:
            class_path: models.models.mmclassifiers.ImageTransformerDistillationLabelClassifier
            init_args:
                teacher_classifier:
                    init_args:
                        num_labels: 6
                        fusion_transformer_cfg:
                            transformer_cfg:
                                num_patches: 7
                        head:
                            num_classes: 7
                fusion_transformer_cfg:
                    transformer_cfg:
                        num_patches: 4
                head:
                    num_classes: 7