__base__:
    - resnet50_transformer_with_label_cataract.yaml

model:
    init_args:
        model:
            init_args:
                head:
                    type: StackedLinearClsHead
                    mid_channels: [128]
