model:
    init_args:
        optimizer_config:
            optimizer:
                type: SGD
                lr: 2.0e-2
                momentum: 0.9
                weight_decay: 1e-4
            lr_scheduler:
                scheduler:
                    type: MultiStepLR
                    milestones: [ 8, 11 ]
                warmup_config:
                    warmup_iters: 500

trainer:
    max_epochs: 12
