__base__: schedule_1x.yaml

model:
    init_args:
        optimizer_config:
            lr_scheduler:
                scheduler:
                    milestones: [ 16, 19 ]

trainer:
    max_epochs: 20
