__base__: cataract_classification.yaml

trainer:
    num_folds: 5

data:
    class_path: datasets.KFoldMMDetDataSetAdapter
    init_args:
        dataset_cfg:
            ann_file: data/cataract/C_all_data_add_2.csv