__base__:
    - ../../default_runtime.yaml
    - ../../models/faster_rcnn/faster_rcnn_r50_fpn.yaml
    - ../../datasets/tct/tct_detection.yaml
    - ../../schedules/schedule_1x.yaml

model:
    init_args:
        model:
            init_args:
                roi_head:
                    bbox_head:
                        num_classes: 5

data:
    init_args:
        data_loader_config:
            batch_size: 8
            num_workers: 8
            prefetch_factor: 2
