__base__:
    - ../../default_runtime.yaml
    - ../../models/faster_rcnn/faster_rcnn_r50_fpn.yaml
    - ../../datasets/coco/coco_detection.yaml
    - ../../schedules/schedule_1x.yaml

trainer:
    # debug
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    fast_dev_run: false
    overfit_batches: 0.0

data:
    init_args:
        data_loader_config:
            batch_size: 4
            num_workers: 4
            prefetch_factor: 2
