__base__:
    - ../../default_runtime.yaml
    - ../../models/faster_rcnn/faster_rcnn_r50_fpn.yaml
    - ../../datasets/DualCervix/DualCervixDetection/DualCervixDetection_color.yaml
    - ../../schedules/schedule_1x.yaml

model:
    init_args:
        model:
            init_args:
                roi_head:
                    bbox_head:
                        num_classes: 1

trainer:
    # debug
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    fast_dev_run: false
    overfit_batches: 0.0

data:
    init_args:
        data_loader_config:
            batch_size: 16
            num_workers: 8
            prefetch_factor: 2
