__base__:
    - ../../default_runtime.yaml
    - ../../models/faster_rcnn/faster_rcnn_r50_fpn.yaml
    - ../../datasets/coco/coco_detection.yaml
    - ../../schedules/schedule_1x.yaml

data:
    init_args:
        data_loader_config:
            batch_size: 4
            num_workers: 4
            prefetch_factor: 2
