__base__: ../DualCervix_color.yaml

__import__:
    import_gen_segmentation_from_bbox_transform: &import_gen_segmentation_from_bbox_transform
        type: GenSegmentationFromBBox
        num_classes: 1

data:
    init_args:
        dataset_cfg:
            pipeline:
                acid:
                    insert_item:
                        - [ 5, *import_gen_segmentation_from_bbox_transform ]
                iodine:
                    insert_item:
                        - [ 5, *import_gen_segmentation_from_bbox_transform ]