model:
    class_path: models.models.pix2pix_model.Pix2PixModel
    init_args:
        netG:
            class_path: models.layers.GAN_networks.UnetGenerator
            init_args:
                input_nc: 3
                output_nc: 3
                ngf: 64
                use_dropout: false
                num_downs: 8
                norm_layer: torch.nn.BatchNorm2d
        netD:
            class_path: models.layers.GAN_networks.NLayerDiscriminator
            init_args:
                input_nc: 6
                ndf: 64
                n_layers: 3
                norm_layer: torch.nn.BatchNorm2d
        lambda_L1: 1
        lambda_GAN: 0
        lambda_D: 1
        normalize_config:
            acid:
                mean: [ 107.5614013671875, 108.2771987915039, 157.57847595214844 ]
                std: [ 15.73247241973877, 13.8170747756958, 24.39257049560547 ]
            iodine:
                mean: [ 43.90464401245117, 71.49726867675781, 123.6583023071289 ]
                std: [ 14.21172046661377, 18.04821014404297, 34.25565719604492 ]
        loss_config:
            gan:
                module:
                    class_path: models.losses.losses.GANLoss
                    init_args:
                        gan_mode: vanilla
                weight: 1.0
            L1:
                module:
                    class_path: torch.nn.L1Loss
                weight: 1.0

optimizer_config:
    optimizer:
        class_path: torch.optim.Adam
        init_args:
            lr: 1.0e-5
            weight_decay: 0.01
    lr_scheduler:
        scheduler:
            class_path: torch.optim.lr_scheduler.StepLR
            init_args:
                gamma: 0.1
                step_size: 100
        warmup_config:
            warmup_iters: 500