data:
    class_path: datasets.MMDetDataSetAdapter
    init_args:
        dataset_cfg:
            type: CocoDataset
            pipeline:
                -   type: LoadImageFromFile
                    color_type: color
                -   type: LoadAnnotations
                    with_bbox: true
                -   type: Resize
                    img_scale: !!python/tuple [ 1333, 800 ]
                    keep_ratio: true
                -   type: RandomFlip
                    flip_ratio: 0.5
                -   type: Normalize
                    mean: [ 123.675, 116.28, 103.53 ]
                    std: [ 58.395, 57.12, 57.375 ]
                    to_rgb: true
                -   type: Pad
                    size_divisor: 32
                -   type: DefaultFormatBundle
                -   type: Collect
                    keys: [ img, gt_bboxes, gt_labels ]
            data_root: data/coco
            ann_file: annotations/instances_${split}2017.json
            img_prefix: ${split}2017
        split_format_to: [ ann_file, img_prefix ]
        data_loader_config:
            batch_size: 32
            num_workers: 8
            prefetch_factor: 2
            pin_memory: true

trainer:
    callbacks:
        change_item:
            -   - 0
                -   init_args:
                        monitor: val/map_50
                        filename: 'epoch:{epoch}-val_map_50:{val/map_50:.4g}'
                        mode: max